package com.dadiyw.ce16.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * Database Table Remarks:
 *   数据库此表没有注释
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table DW_CE16_MARTKET_ACTIVE_INFO
 */


@ApiModel(value="数据库此表没有注释")
@Data
public class MartketActiveInfo implements Serializable {
    @ApiModelProperty(value = "商户ID")
    private String midCode;

    @ApiModelProperty(value = "机构ID")
    private String shopCode;

    @ApiModelProperty(value = "营销活动ID")
    private String activeCode;

    @ApiModelProperty(value = "营销活动类型")
    private String marketActiveType;

    @ApiModelProperty(value = "开始日期")
    private Date startDate;

    @ApiModelProperty(value = "结束日期")
    private Date endDate;

    @ApiModelProperty(value = "活动状态")
    private String activeStatus;

    private static final long serialVersionUID = 1L;

    public String getMidCode() {
        return midCode;
    }

    public void setMidCode(String midCode) {
        this.midCode = midCode == null ? null : midCode.trim();
    }

    public String getShopCode() {
        return shopCode;
    }

    public void setShopCode(String shopCode) {
        this.shopCode = shopCode == null ? null : shopCode.trim();
    }

    public String getActiveCode() {
        return activeCode;
    }

    public void setActiveCode(String activeCode) {
        this.activeCode = activeCode == null ? null : activeCode.trim();
    }

    public String getMarketActiveType() {
        return marketActiveType;
    }

    public void setMarketActiveType(String marketActiveType) {
        this.marketActiveType = marketActiveType == null ? null : marketActiveType.trim();
    }

    public Date getStartDate() {
        return startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getEndDate() {
        return endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public String getActiveStatus() {
        return activeStatus;
    }

    public void setActiveStatus(String activeStatus) {
        this.activeStatus = activeStatus == null ? null : activeStatus.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", midCode=").append(midCode);
        sb.append(", shopCode=").append(shopCode);
        sb.append(", activeCode=").append(activeCode);
        sb.append(", marketActiveType=").append(marketActiveType);
        sb.append(", startDate=").append(startDate);
        sb.append(", endDate=").append(endDate);
        sb.append(", activeStatus=").append(activeStatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}