package com.dadiyw.ce16.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * Database Table Remarks:
 *   数据库此表没有注释
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ce17_zmengzhu_data_detail
 */


@ApiModel(value="数据库此表没有注释")
@Data
public class ViewDetail implements Serializable {
    @ApiModelProperty(value = "成功为200")
    private String CODE;

    @ApiModelProperty(value = "成功返回ok")
    private String MSG;

    @ApiModelProperty(value = "频道ID")
    private String CHANNEL_ID;

    @ApiModelProperty(value = "活动ID")
    private String WEBINAR_ID;

    @ApiModelProperty(value = "用户ID")
    private String UID;

    @ApiModelProperty(value = "首次进入时间")
    private String JOIN_TIME;

    @ApiModelProperty(value = "最后离开时间")
    private String LEAVE_TIME;

    @ApiModelProperty(value = "累计观看时长")
    private String DURATION;

    @ApiModelProperty(value = "访问IP")
    private String IP;

    @ApiModelProperty(value = "观看终端")
    private String PLATFORM;

    @ApiModelProperty(value = "地理位置")
    private String AREA;

    @ApiModelProperty(value = "创建时间")
    private String CREATED_AT;

    @ApiModelProperty(value = "活动开始时间")
    private String WEBINAR_START_TIME;

    @ApiModelProperty(value = "邀请用户")
    private String INVITE_UID;

    @ApiModelProperty(value = "邀请用户")
    private String INVITE_NICKNAME;

    @ApiModelProperty(value = "昵称")
    private String NICKNAME;

    @ApiModelProperty(value = "手机号")
    private String PHONE;

    @ApiModelProperty(value = "初始化第三方用户标识")
    private String ORIGIN_UNIQUE_ID;

    @ApiModelProperty(value = "总量")
    private String TOTAL;

    @ApiModelProperty(value = "接口类型1直播2回放")
    private String API_TYPE;

    @ApiModelProperty(value = "数据中心数据抽取入库时间")
    private Date DATACENTER_INSERT_TIME;

    private static final long serialVersionUID = 1L;

    public String getCODE() {
        return CODE;
    }

    public void setCODE(String CODE) {
        this.CODE = CODE == null ? null : CODE.trim();
    }

    public String getMSG() {
        return MSG;
    }

    public void setMSG(String MSG) {
        this.MSG = MSG == null ? null : MSG.trim();
    }

    public String getCHANNEL_ID() {
        return CHANNEL_ID;
    }

    public void setCHANNEL_ID(String CHANNEL_ID) {
        this.CHANNEL_ID = CHANNEL_ID == null ? null : CHANNEL_ID.trim();
    }

    public String getWEBINAR_ID() {
        return WEBINAR_ID;
    }

    public void setWEBINAR_ID(String WEBINAR_ID) {
        this.WEBINAR_ID = WEBINAR_ID == null ? null : WEBINAR_ID.trim();
    }

    public String getUID() {
        return UID;
    }

    public void setUID(String UID) {
        this.UID = UID == null ? null : UID.trim();
    }

    public String getJOIN_TIME() {
        return JOIN_TIME;
    }

    public void setJOIN_TIME(String JOIN_TIME) {
        this.JOIN_TIME = JOIN_TIME == null ? null : JOIN_TIME.trim();
    }

    public String getLEAVE_TIME() {
        return LEAVE_TIME;
    }

    public void setLEAVE_TIME(String LEAVE_TIME) {
        this.LEAVE_TIME = LEAVE_TIME == null ? null : LEAVE_TIME.trim();
    }

    public String getDURATION() {
        return DURATION;
    }

    public void setDURATION(String DURATION) {
        this.DURATION = DURATION == null ? null : DURATION.trim();
    }

    public String getIP() {
        return IP;
    }

    public void setIP(String IP) {
        this.IP = IP == null ? null : IP.trim();
    }

    public String getPLATFORM() {
        return PLATFORM;
    }

    public void setPLATFORM(String PLATFORM) {
        this.PLATFORM = PLATFORM == null ? null : PLATFORM.trim();
    }

    public String getAREA() {
        return AREA;
    }

    public void setAREA(String AREA) {
        this.AREA = AREA == null ? null : AREA.trim();
    }

    public String getCREATED_AT() {
        return CREATED_AT;
    }

    public void setCREATED_AT(String CREATED_AT) {
        this.CREATED_AT = CREATED_AT == null ? null : CREATED_AT.trim();
    }

    public String getWEBINAR_START_TIME() {
        return WEBINAR_START_TIME;
    }

    public void setWEBINAR_START_TIME(String WEBINAR_START_TIME) {
        this.WEBINAR_START_TIME = WEBINAR_START_TIME == null ? null : WEBINAR_START_TIME.trim();
    }

    public String getINVITE_UID() {
        return INVITE_UID;
    }

    public void setINVITE_UID(String INVITE_UID) {
        this.INVITE_UID = INVITE_UID == null ? null : INVITE_UID.trim();
    }

    public String getINVITE_NICKNAME() {
        return INVITE_NICKNAME;
    }

    public void setINVITE_NICKNAME(String INVITE_NICKNAME) {
        this.INVITE_NICKNAME = INVITE_NICKNAME == null ? null : INVITE_NICKNAME.trim();
    }

    public String getNICKNAME() {
        return NICKNAME;
    }

    public void setNICKNAME(String NICKNAME) {
        this.NICKNAME = NICKNAME == null ? null : NICKNAME.trim();
    }

    public String getPHONE() {
        return PHONE;
    }

    public void setPHONE(String PHONE) {
        this.PHONE = PHONE == null ? null : PHONE.trim();
    }

    public String getORIGIN_UNIQUE_ID() {
        return ORIGIN_UNIQUE_ID;
    }

    public void setORIGIN_UNIQUE_ID(String ORIGIN_UNIQUE_ID) {
        this.ORIGIN_UNIQUE_ID = ORIGIN_UNIQUE_ID == null ? null : ORIGIN_UNIQUE_ID.trim();
    }

    public String getTOTAL() {
        return TOTAL;
    }

    public void setTOTAL(String TOTAL) {
        this.TOTAL = TOTAL == null ? null : TOTAL.trim();
    }

    public String getAPI_TYPE() {
        return API_TYPE;
    }

    public void setAPI_TYPE(String API_TYPE) {
        this.API_TYPE = API_TYPE == null ? null : API_TYPE.trim();
    }

    public Date getDATACENTER_INSERT_TIME() {
        return DATACENTER_INSERT_TIME;
    }

    public void setDATACENTER_INSERT_TIME(Date DATACENTER_INSERT_TIME) {
        this.DATACENTER_INSERT_TIME = DATACENTER_INSERT_TIME;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", CODE=").append(CODE);
        sb.append(", MSG=").append(MSG);
        sb.append(", CHANNEL_ID=").append(CHANNEL_ID);
        sb.append(", WEBINAR_ID=").append(WEBINAR_ID);
        sb.append(", UID=").append(UID);
        sb.append(", JOIN_TIME=").append(JOIN_TIME);
        sb.append(", LEAVE_TIME=").append(LEAVE_TIME);
        sb.append(", DURATION=").append(DURATION);
        sb.append(", IP=").append(IP);
        sb.append(", PLATFORM=").append(PLATFORM);
        sb.append(", AREA=").append(AREA);
        sb.append(", CREATED_AT=").append(CREATED_AT);
        sb.append(", WEBINAR_START_TIME=").append(WEBINAR_START_TIME);
        sb.append(", INVITE_UID=").append(INVITE_UID);
        sb.append(", INVITE_NICKNAME=").append(INVITE_NICKNAME);
        sb.append(", NICKNAME=").append(NICKNAME);
        sb.append(", PHONE=").append(PHONE);
        sb.append(", ORIGIN_UNIQUE_ID=").append(ORIGIN_UNIQUE_ID);
        sb.append(", TOTAL=").append(TOTAL);
        sb.append(", API_TYPE=").append(API_TYPE);
        sb.append(", DATACENTER_INSERT_TIME=").append(DATACENTER_INSERT_TIME);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}